<?php

/* Suporte JS para preços configuráveis */

$helper = Mage::helper('franciscoprado_precoparcelado');
$isActive = $helper->isModuleEnabled();
$showTable = $helper->showTable();
$minParcel = Mage::helper('franciscoprado_precoparcelado')->getMinParcelValue();
$maxNumberMonths = Mage::helper('franciscoprado_precoparcelado')->getMaxNumberMonths();
$interest = Mage::helper('franciscoprado_precoparcelado')->getInterest();
$text = Mage::helper('franciscoprado_precoparcelado')->getText();
$tableText = Mage::helper('franciscoprado_precoparcelado')->getTableText();
$addJquery = Mage::helper('franciscoprado_precoparcelado')->addJquery();

if ($isActive): ?>
<script>
    /* preco parcelado */
    var showTable = <?php echo $showTable ? 'true' : 'false'; ?>;
    var minParcel = <?php echo $minParcel ?>;
    var maxNumberMonths = <?php echo $maxNumberMonths ?>;
    var interest = <?php echo $interest ?>;
    var ppText = '<?php echo $text ?>';
    var ppTableText = '<?php echo $tableText ?>';
    var ppId = '<?php echo Mage::registry('current_product')->getId() ?>';
</script>
    <?php
    if ($addJquery):
    ?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <?php endif; ?>
<script src="<?php echo $this->getSkinUrl('js/precoparcelado.js') ?>"></script>
<?php endif; ?>